const data = {
    products: [
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'Nike Slim Shirt Red',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 150,
            brand: 'Nike',
            rating: 4.8,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'Puma Pants',
            category: 'Pants',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Adidas Pants',
            category: 'Pants',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'low quality product',
        },
    ]
}

export default data;